using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Numerics;
using Bonobo.Bepuphysics2;
using Bonobo.Bepuphysics2.Collidables;
using Bonobo.Bepuphysics2.CollisionDetection;
using Bonobo.Bepuphysics2.Constraints;
using Bonobo.BepuUtilities;
using Bonobo.BepuUtilities.Collections;
using Bonobo.BepuUtilities.Memory;

namespace Game.BepuDemos.Demos;

/// <summary>
///     Refers to a collidable, or a child within a collidable (ported from the upstream
///     <c>CollisionTrackingDemo</c>, BepuPhysics2, Apache-2.0, Ross Nordby).
/// </summary>
public struct ContactSource : IEqualityComparerRef<ContactSource>, IEquatable<ContactSource>
{
    public CollidableReference Collidable;
    public int ChildIndex;

    public bool Equals(ref ContactSource a, ref ContactSource b) => a.Collidable == b.Collidable && a.ChildIndex == b.ChildIndex;
    public int Hash(ref ContactSource item) => (int)(item.Collidable.Packed ^ uint.RotateLeft((uint)item.ChildIndex, 16));
    public bool Equals(ContactSource other) => Equals(ref this, ref other);
    public override bool Equals(object? obj) => obj is ContactSource source && Equals(source);
    public override int GetHashCode() => Hash(ref this);
    public static bool operator ==(ContactSource left, ContactSource right) => left.Equals(right);
    public static bool operator !=(ContactSource left, ContactSource right) => !(left == right);
    public static implicit operator ContactSource(CollidableReference collidable) => new() { Collidable = collidable, ChildIndex = -1 };
}

/// <summary>Stores contacts generated by the narrow phase for a pair.</summary>
public struct PairCollision
{
    /// <summary>
    ///     True when the 'other' collidable is stored in the first slot of the pair (contact data
    ///     is calibrated relative to collidable A).
    /// </summary>
    public bool OtherIsAInPair;

    public NonconvexContactManifold Contacts;
}

/// <summary>
///     Tracks collisions for a set of collidables (or their children) and stores the current and
///     previous pair state for deferred analysis (ported from the upstream
///     <c>CollisionTrackingDemo</c>). Single-threaded test bed: one worker cache flushed after
///     collision detection.
/// </summary>
public class CollisionTracker : IDisposable
{
    private BufferPool _pool;
    private Simulation _simulation = null!;

    public CollisionTracker(BufferPool pool)
    {
        _pool = pool;
        Tracked = new QuickDictionary<ContactSource, TrackedPairs, ContactSource>(16, pool);
    }

    public void Initialize(Simulation simulation)
    {
        _simulation = simulation;
        // Monitor sleeping state after the sleeper ran but before the narrow phase (upstream).
        simulation.Timestepper.BeforeCollisionDetection += PrepareForNextTimestep;
        simulation.Timestepper.CollisionsDetected += Flush;
    }

    public void Dispose()
    {
        if (Tracked.Keys.Allocated)
        {
            for (var i = 0; i < Tracked.Count; ++i) Tracked.Values[i].Pairs.Dispose(_pool);
            Tracked.Dispose(_pool);
            _simulation.Timestepper.BeforeCollisionDetection -= PrepareForNextTimestep;
            _simulation.Timestepper.CollisionsDetected -= Flush;
        }
    }

    public struct TrackedPairs
    {
        public QuickDictionary<ContactSource, PairCollision, ContactSource> Pairs;
        public QuickDictionary<ContactSource, PairCollision, ContactSource> PreviousPairs;

        public TrackedPairs(BufferPool pool)
        {
            Pairs = new QuickDictionary<ContactSource, PairCollision, ContactSource>(16, pool);
            PreviousPairs = new QuickDictionary<ContactSource, PairCollision, ContactSource>(16, pool);
        }

        public void Dispose(BufferPool pool)
        {
            Pairs.Dispose(pool);
            PreviousPairs.Dispose(pool);
        }
    }

    /// <summary>Maps tracked objects to the contacts associated with them.</summary>
    public QuickDictionary<ContactSource, TrackedPairs, ContactSource> Tracked;

    public void Track(ContactSource target)
    {
        if (Tracked.ContainsKey(target)) throw new ArgumentException("Object already tracked.");
        Tracked.Add(target, new TrackedPairs(_pool), _pool);
    }

    private struct WorkerPairContacts
    {
        public ContactSource Self;
        public ContactSource Other;
        public PairCollision Collision;
    }

    private Buffer<QuickList<WorkerPairContacts>> _workerCaches;

    private void PrepareForNextTimestep(float dt, IThreadDispatcher dispatcher)
    {
        for (var i = 0; i < Tracked.Count; ++i)
        {
            ref var tracked = ref Tracked.Values[i];
            var collidable = Tracked.Keys[i].Collidable;
            if (collidable.Mobility != CollidableMobility.Static && _simulation.Bodies[collidable.BodyHandle].Awake)
            {
                Helpers.Swap(ref tracked.Pairs, ref tracked.PreviousPairs);
                tracked.Pairs.FastClear();
            }
            else
            {
                for (var j = tracked.Pairs.Count - 1; j >= 0; --j)
                {
                    var other = tracked.Pairs.Keys[j];
                    if (other.Collidable.Mobility == CollidableMobility.Static || !_simulation.Bodies[other.Collidable.BodyHandle].Awake) continue;
                    tracked.PreviousPairs.AddAndReplace(other, tracked.Pairs.Values[j], _pool);
                    tracked.Pairs.FastRemove(other);
                }
            }
        }

        const int initialWorkerCapacity = 512;
        _workerCaches = new Buffer<QuickList<WorkerPairContacts>>(1, _pool);
        _workerCaches[0] = new QuickList<WorkerPairContacts>(initialWorkerCapacity, _pool);
    }

    private void FlushWorkerCache(ref QuickList<WorkerPairContacts> cache, BufferPool pool)
    {
        for (var j = 0; j < cache.Count; ++j)
        {
            ref var entry = ref cache[j];
            Tracked.GetTableIndices(ref entry.Self, out _, out var elementIndex);
            Tracked.Values[elementIndex].Pairs.Add(entry.Other, entry.Collision, pool);
        }

        cache.Dispose(pool);
    }

    private void Flush(float dt, IThreadDispatcher threadDispatcher)
    {
        FlushWorkerCache(ref _workerCaches[0], _pool);
        _workerCaches.Dispose(_pool);
    }

    private void ReportContacts<TContacts>(int workerIndex, ContactSource self, ContactSource other, bool otherIsA, ref TContacts contacts)
        where TContacts : unmanaged, IContactManifold<TContacts>
    {
        if (!Tracked.ContainsKey(self)) return;

        ref var pairContacts = ref _workerCaches[workerIndex].Allocate(_pool);
        pairContacts.Self = self;
        pairContacts.Other = other;
        pairContacts.Collision.OtherIsAInPair = otherIsA;
        if (typeof(TContacts) == typeof(ConvexContactManifold))
        {
            ref var convex = ref Unsafe.As<TContacts, ConvexContactManifold>(ref contacts);
            for (var i = 0; i < contacts.Count; ++i)
            {
                ref var targetContact = ref Unsafe.Add(ref pairContacts.Collision.Contacts.Contact0, i);
                convex.GetContact(i, out targetContact.Offset, out targetContact.Normal, out targetContact.Depth, out targetContact.FeatureId);
            }

            pairContacts.Collision.Contacts.Count = contacts.Count;
            pairContacts.Collision.Contacts.OffsetB = convex.OffsetB;
        }
        else
        {
            pairContacts.Collision.Contacts = Unsafe.As<TContacts, NonconvexContactManifold>(ref contacts);
        }
    }

    /// <summary>Notifies the tracker of a collision between collidable children.</summary>
    public void ReportChildContacts(CollidableReference collidableA, int childIndexA, CollidableReference collidableB, int childIndexB, int workerIndex, ref ConvexContactManifold contacts)
    {
        var a = new ContactSource { Collidable = collidableA, ChildIndex = childIndexA };
        var b = new ContactSource { Collidable = collidableB, ChildIndex = childIndexB };
        ReportContacts(workerIndex, a, b, false, ref contacts);
        ReportContacts(workerIndex, b, a, true, ref contacts);
    }

    /// <summary>Notifies the tracker of a collision between collidables.</summary>
    public void ReportContacts<TManifold>(CollidableReference collidableA, CollidableReference collidableB, int workerIndex, ref TManifold contacts)
        where TManifold : unmanaged, IContactManifold<TManifold>
    {
        var a = new ContactSource { Collidable = collidableA, ChildIndex = -1 };
        var b = new ContactSource { Collidable = collidableB, ChildIndex = -1 };
        ReportContacts(workerIndex, a, b, false, ref contacts);
        ReportContacts(workerIndex, b, a, true, ref contacts);
    }
}

/// <summary>Narrow phase callbacks that hand every manifold to a <see cref="CollisionTracker"/>.</summary>
public struct CollisionTrackingCallbacks : INarrowPhaseCallbacks
{
    private CollisionTracker _collisionTracker;

    public CollisionTrackingCallbacks(CollisionTracker collisionTracker)
    {
        _collisionTracker = collisionTracker;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool AllowContactGeneration(int workerIndex, CollidableReference a, CollidableReference b, ref float speculativeMargin) => true;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool AllowContactGeneration(int workerIndex, CollidablePair pair, int childIndexA, int childIndexB) => true;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ConfigureContactManifold<TManifold>(int workerIndex, CollidablePair pair, ref TManifold manifold, out PairMaterialProperties pairMaterial)
        where TManifold : unmanaged, IContactManifold<TManifold>
    {
        pairMaterial.FrictionCoefficient = 1f;
        pairMaterial.MaximumRecoveryVelocity = 2f;
        pairMaterial.SpringSettings = new SpringSettings(30f, 1f);
        _collisionTracker.ReportContacts(pair.A, pair.B, workerIndex, ref manifold);
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool ConfigureContactManifold(int workerIndex, CollidablePair pair, int childIndexA, int childIndexB, ref ConvexContactManifold manifold)
    {
        _collisionTracker.ReportChildContacts(pair.A, childIndexA, pair.B, childIndexB, workerIndex, ref manifold);
        return true;
    }

    public void Initialize(Simulation simulation) => _collisionTracker.Initialize(simulation);

    public void Dispose()
    {
    }
}
